services:

  zabbix-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_ROOT_PASSWORD: zabbix
    networks:
      - zabbix

  zabbix-server:
    image: zabbix/zabbix-server-mysql:7.0-alpine-latest
    depends_on:
      - zabbix-db
    environment:
      DB_SERVER_HOST: zabbix-db
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_ROOT_PASSWORD: zabbix
    ports:
      - "10051:10051"
    networks:
      - zabbix

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:7.0-alpine-latest
    depends_on:
      - zabbix-db
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: zabbix-db
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_ROOT_PASSWORD: zabbix
    ports:
      - "8080:8080"
    networks:
      - zabbix

networks:
  zabbix:
    driver: bridge
